import { useState } from 'react';
import { View, Text, ScrollView, StyleSheet, Platform, Linking } from 'react-native';
import Constants from 'expo-constants';
import * as Clipboard from 'expo-clipboard';
import { Pressable } from '../components/Pressable';
import { Icon } from '../components/Icon';
import { Label, Body, Title, Rule, GhostButton, Index } from '../components/kit';
import { TAB_BAR_CLEARANCE } from '../components/TabBar';
import { useAuth } from '../contexts/AuthContext';
import { getCachedUsage } from '../services/usageCache';
import { colors, spacing, font, tracking, typeface, themed } from '../constants/theme';

/** The one place this address is written down. App Store Connect's "Support
 *  URL" field needs the same one — see docs/SUPPORT.html. */
export const SUPPORT_EMAIL = 'savehere.support@gmail.com';

/**
 * Things every support reply otherwise has to ask for, and that the user has no
 * good way to find. Prefilling them is the difference between one round-trip
 * and four.
 *
 * ⚠️ Nothing here is sent anywhere by the app — it is composed into a draft in
 * the user's own mail client, which they read and send themselves. The account
 * email is theirs and already on screen elsewhere; no other identifier is
 * included, and the AI tier/usage numbers are there because "I'm out of AI
 * actions" is the most likely reason to write in the first place.
 */
function diagnostics(email: string | null, tier: string | null): string {
  const app = Constants.expoConfig?.version ?? 'unknown';
  const build = Platform.select({
    ios: Constants.expoConfig?.ios?.buildNumber,
    android: String(Constants.expoConfig?.android?.versionCode ?? ''),
    default: 'web',
  }) || 'unknown';
  return [
    '',
    '',
    '— — — — — — — — — —',
    'Please leave the lines below — they help us find the problem.',
    `Account: ${email ?? 'not signed in'}`,
    `Plan: ${tier ?? 'unknown'}`,
    `App: ${app} (${build})`,
    `Platform: ${Platform.OS} ${String(Platform.Version ?? '')}`.trim(),
  ].join('\n');
}

const TOPICS: { title: string; detail: string; subject: string }[] = [
  {
    title: 'A save failed, or came back empty',
    detail:
      'Send the link you tried to save. Some posts are private, deleted, or behind a login wall, and there is nothing readable in them — but if a public link failed, that is a bug and we want it.',
    subject: 'A save failed',
  },
  {
    title: 'A summary is wrong or missing',
    detail:
      'Summaries are generated by AI and can be wrong or thin — you can edit them and add your own notes at any time. If one is badly wrong, send the save so we can look at what the reel actually contained.',
    subject: 'Summary problem',
  },
  {
    title: 'Billing, Pro, or a refund',
    detail:
      'Subscriptions are billed by Apple, not by us, so refunds go through Apple. We can still fix anything on the account side — a plan that did not activate, or a charge you do not recognise.',
    subject: 'Billing question',
  },
  {
    title: 'Delete my account and data',
    detail:
      'You can do this yourself: Menu → Delete account. It removes every saved link, summary, note, to-do, recipe and workout plan, and the account itself. Write in if it does not work.',
    subject: 'Account deletion',
  },
  {
    title: 'Something else',
    detail:
      'Bugs, ideas, a feature you expected to find, or a save the app handled badly. One person reads these.',
    subject: 'Support request',
  },
];

/**
 * The cases that generate support mail but are working as designed. Every one
 * of these is documented behaviour somewhere in the repo; a user has no way to
 * know that, so they write in. Answering here costs nothing and is faster for
 * them than a reply would be.
 */
const KNOWN: { q: string; a: string }[] = [
  {
    q: 'A reel saved, but there is no summary',
    a: 'Some posts carry no readable text at all — the words are spoken aloud or burned into the video, and neither can be read automatically. The link, title and picture are still saved. Paste the post’s caption into Notes on that save and tap Re-summarize, and it will work.',
  },
  {
    q: 'It says my AI actions are used up',
    a: 'Summaries, recipes, workouts and questions share one daily allowance that resets every day — the screen tells you the exact time it comes back. Saving links is never rationed on any plan, so you can keep saving and summarise later.',
  },
  {
    q: 'A saved card lost its picture',
    a: 'Instagram’s preview images expire after a few days by design. The app now fetches a fresh one automatically when it notices, so pull to refresh and it should return. If the post was deleted or made private, the picture is gone for good — the save itself still works.',
  },
  {
    q: 'Sharing from Instagram does nothing visible',
    a: 'That is intentional: sharing saves in the background so you stay in Instagram instead of being pulled into another app. You get a notification when it lands, and the save appears in your library. If no notification arrives, tell us.',
  },
  {
    q: 'A summary is wrong',
    a: 'Summaries are generated by AI and can be wrong or thin — they are a starting point, not a source of truth. You can edit any summary and add your own notes. If one is badly wrong, send us the link so we can look at what the post actually contained.',
  },
];

export default function SupportScreen() {
  const { email } = useAuth();
  const tier = getCachedUsage()?.tier ?? null;
  const [copied, setCopied] = useState(false);
  const [open, setOpen] = useState<string | null>(null);
  const [mailFailed, setMailFailed] = useState(false);

  /**
   * ⚠️ `Linking.openURL` DIRECTLY — deliberately NOT `services/openLink`.
   *
   * That helper prechecks non-http schemes with `canOpenURL`, which on Android
   * 11+ returns false for any scheme absent from a `<queries>` manifest block
   * whether or not a handler exists. Our manifest declares none, so routing
   * `mailto:` through it would refuse to open on every modern Android phone
   * without ever trying — the exact bug that made the Watch button dead
   * (TODO.md, round 1 item 11). Its failure copy is also about saved reels,
   * which would be nonsense here.
   *
   * A failure is handled in place: the address stays on screen, copyable.
   */
  const mail = (subject: string) => {
    const body = encodeURIComponent(diagnostics(email ?? null, tier));
    const url = `mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent(`Findable — ${subject}`)}&body=${body}`;
    Linking.openURL(url).then(() => setMailFailed(false)).catch(() => setMailFailed(true));
  };

  /**
   * ⚠️ THE COPY BUTTON IS NOT A NICETY. `mailto:` opens nothing on a device
   * with no mail client configured, and on web it depends on a handler being
   * registered — both fail silently. Without a way to just take the address,
   * a user in that state has no route to support at all, which is precisely
   * what App Store guideline 1.5 requires the app to provide.
   */
  const copyAddress = async () => {
    await Clipboard.setStringAsync(SUPPORT_EMAIL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <View style={styles.screen}>
      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Title>Something not working?</Title>
        <Body style={styles.sub}>
          Write to us and you'll get a reply from a person. Include the link you were saving if a
          save is involved — it is the single most useful thing you can send.
        </Body>

        {/* The address, plainly, before anything else. Someone who arrived here
            angry should not have to read a page to find it. */}
        <View style={styles.addressBox}>
          <Label wide>Support</Label>
          <Text style={styles.address} selectable>{SUPPORT_EMAIL}</Text>
          <View style={styles.addressActions}>
            <GhostButton label="Write to support" trailing="→" onPress={() => mail('Support request')} style={styles.flexBtn} />
            <Pressable style={styles.copy} onPress={copyAddress} accessibilityLabel="Copy the support email address">
              <Icon name={copied ? 'checkmark' : 'copy'} size={15} color={colors.textPrimary} />
              <Text style={styles.copyLabel}>{copied ? 'COPIED' : 'COPY'}</Text>
            </Pressable>
          </View>
          <Body style={styles.fine}>
            {mailFailed
              ? "This device has no mail app set up, so we couldn't open a draft. Copy the address above and write from wherever you read email."
              : "Opening the mail app adds your account email, plan and app version to the draft, so we don't have to ask. Nothing is sent until you send it."}
          </Body>
        </View>

        <Label wide style={styles.section}>What can we help with</Label>
        <Rule />
        {TOPICS.map((t, i) => (
          <View key={t.title}>
            <Pressable style={styles.row} onPress={() => mail(t.subject)}>
              <Index n={i + 1} style={styles.index} />
              <View style={styles.rowText}>
                <Text style={styles.rowTitle}>{t.title}</Text>
                <Body style={styles.rowDetail}>{t.detail}</Body>
              </View>
              <Icon name="chevron-right" size={15} color={colors.textTertiary} />
            </Pressable>
            <Rule />
          </View>
        ))}

        {/* ── Self-serve first ──────────────────────────────────────────────
            An industrial support page answers the common cases before it asks
            for an email, because most people writing in are describing expected
            behaviour they had no way to recognise as expected. Each of these is
            a real thing this app does that reads as a bug. */}
        <Label wide style={styles.section}>Probably not a bug</Label>
        <Rule />
        {KNOWN.map(k => (
          <View key={k.q}>
            <Pressable style={styles.faq} onPress={() => setOpen(open === k.q ? null : k.q)}>
              <Body tone="primary" style={styles.faqQ}>{k.q}</Body>
              <Icon
                name="chevron-right" size={14} color={colors.textTertiary}
                style={{ transform: [{ rotate: open === k.q ? '90deg' : '0deg' }] }}
              />
            </Pressable>
            {open === k.q && <Body style={styles.faqA}>{k.a}</Body>}
            <Rule />
          </View>
        ))}

        <Label wide style={styles.section}>Response times</Label>
        <Rule />
        <Body style={styles.note}>
          Findable is built and supported by one person, so replies come in days rather than
          minutes — and they come from a human, not a queue. If something is losing your saves or
          charging you wrongly, put that in the subject line and it goes to the front.
        </Body>

        <Label wide style={styles.section}>Your data</Label>
        <Rule />
        <Body style={styles.note}>
          Writing in shares only what you put in the message plus the account and version lines
          above. Support cannot read your library, your notes or your saved links. You can delete
          your account and everything in it at any time from Menu → Delete account, without asking
          anyone.
        </Body>
      </ScrollView>
    </View>
  );
}

const styles = themed(() => StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: TAB_BAR_CLEARANCE + spacing.xl,
  },
  sub: { marginTop: spacing.md, fontSize: font.sm, lineHeight: 20 },

  addressBox: {
    marginTop: spacing.xl,
    borderWidth: 1,
    borderColor: colors.ghostLine,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  address: {
    color: colors.textPrimary,
    fontFamily: typeface.display,
    fontSize: font.lg,
    letterSpacing: tracking.heading,
  },
  addressActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.sm },
  flexBtn: { flex: 1 },
  copy: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.ghostLine,
    paddingVertical: 15,
    paddingHorizontal: spacing.md,
  },
  copyLabel: {
    color: colors.textPrimary,
    fontFamily: typeface.label,
    fontSize: font.xs,
    letterSpacing: tracking.labelWide,
  },
  fine: { fontSize: font.sm, lineHeight: 19, marginTop: spacing.xs },

  section: { marginTop: spacing.xl, marginBottom: spacing.sm },
  row: { flexDirection: 'row', gap: spacing.md, alignItems: 'flex-start', paddingVertical: spacing.lg },
  index: { width: 22, paddingTop: 4 },
  rowText: { flex: 1, minWidth: 0, gap: spacing.sm },
  rowTitle: {
    color: colors.textPrimary,
    fontFamily: typeface.display,
    fontSize: font.md,
    letterSpacing: tracking.heading,
  },
  rowDetail: { fontSize: font.sm, lineHeight: 20 },

  note: { fontSize: font.sm, lineHeight: 20, paddingTop: spacing.md },

  faq: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: spacing.md,
  },
  faqQ: { flex: 1, fontSize: font.sm },
  faqA: { fontSize: font.sm, lineHeight: 20, paddingBottom: spacing.md },
}));
