"""baseline schema

Revision ID: 9aa25548aadb
Revises: 
Create Date: 2026-07-21 07:27:34.981451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa25548aadb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_action_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_action_log_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_action_log_user_id'), ['user_id'], unique=False)

    op.create_table('ai_usage',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_table('extraction_cache',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('best_text', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('needs_audio', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('trial_started_at', sa.DateTime(), nullable=False),
    sa.Column('trial_extra_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('summary_status', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('summarize_count', sa.Integer(), nullable=False),
    sa.Column('tasks_count', sa.Integer(), nullable=False),
    sa.Column('workout_count', sa.Integer(), nullable=False),
    sa.Column('itinerary_count', sa.Integer(), nullable=False),
    sa.Column('itinerary', sa.JSON(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reels_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_reels_user_id'), ['user_id'], unique=False)

    op.create_table('trial_grants',
    sa.Column('email_hash', sa.String(), nullable=False),
    sa.Column('trial_started_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email_hash')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reel_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('muscle_group', sa.String(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('workout_name', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('tasks')
    op.drop_table('trial_grants')
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reels_user_id'))
        batch_op.drop_index(batch_op.f('ix_reels_url'))

    op.drop_table('reels')
    op.drop_table('profiles')
    op.drop_table('extraction_cache')
    op.drop_table('ai_usage')
    with op.batch_alter_table('ai_action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_action_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_action_log_day'))

    op.drop_table('ai_action_log')
    # ### end Alembic commands ###
